### PR TITLE
Matlab bf

### PR DESCRIPTION
**Pull request by ljcolling**

### CODE REVIEW

**Comment by Tijl** [comment]
Thanks for this @ljcolling !

From a first glance, we may want to change it to allow matrix input (to run multiple timepoints), but that may be an easy change?

**Comment by ljcolling** [comment]
Sure, that’s an easy change. I’ll code something up (and add some tests for the code), and try push something later today

**Comment by Tijl** [comment]
I just tested it and it nicely gives the exact same results as the R-based version, but about 10x faster :)

One thing I could not work out was the case of a two-sided alternative, where you'd want to set the interval [-Inf Inf] (it hangs on that, not sure why). To fix that, I used:

   A_BIG_NUMBER = 100; 
    if lowerbound==-Inf
        lowerbound = -A_BIG_NUMBER;
    end
    M1 = integral(alt_model,lowerbound,A_BIG_NUMBER);

 The only remaining case is to take the complement of [-0.5 0.5] as interval (which can be done in the R version)..

**Comment by ljcolling** [comment]
I updated it to include a version that takes a matrix as the input and should work with two-sided intervals and for a one-sided interval should spit out the BF and its complement. I've also attached a pdf that just steps through the specification of how BFs of this type are actually calculated (using my `bayesplay` package, which just makes the computations a little less opaque than the `BayesFactor` package). 

[BF_model.pdf](https://github.com/LinaTeichmann1/BFF_repo/files/6733405/BF_model.pdf)

**Comment by Tijl** [comment]
I combined your functions into one, and changed the way the function arguments are handled. Thanks for your code! 

See: https://github.com/LinaTeichmann1/BFF_repo/commit/62bccf1363fbaebbd3a23705d5efe7b1030a6284

**Pull request closed without merging**
